### ISSUE TITLE
Apple Silicon builds

### ISSUE THREAD

**Issue by lebdron** [sonic-visualiser/sonic-visualiser#15]
Hello! Are there plans to provide either separate installer, or universal binary for Apple Silicon (macOS arm64)? I would be glad to help with that.

**Comment by yairchu** [comment]
I attempted building using

```bash
brew install qt5 smlnj meson ninja
./repoint install
meson build
ninja -C build
```

Then I got linker warnings like

```
ld: warning: ignoring file /Users/yairchu/dev/src/sonic-visualiser/sv-dependency-builds/osx/lib/librubberband.a, missing required architecture arm64 in file /Users/yairchu/dev/src/sonic-visualiser/sv-dependency-builds/osx/lib/librubberband.a (2 slices)
```

Followed by link error like

```
Undefined symbols for architecture arm64:
  "kj::InputStream::~InputStream()", referenced from:
      readInputCapnp(piper_vamp::RequestOrResponse::Direction, bool&) in piper-vamp-cpp_vamp-server_convert.cpp.o
```

It seems like the mac build scripts download dependency libraries built for Intel

**Comment by cannam** [comment]
Yes, the `sv-dependency-builds` subrepo contains binaries used for building the distributed package and they are all Intel at this point.

Making an arm64 build has been on my radar and I do have the hardware available for it - although I have to admit that it doesn't feel as urgent as I had expected, simply because the Intel build runs so well on the ARM hardware already.

There are a few considerations here. The first one obviously is that the build is fiddly. It's not all that difficult, but the stuff around getting a working package is *just* trying enough to make it something one has to set aside the time to do properly and to test. And the build process for Mac is very much geared to making the official app package as easily as possible.

The second, particularly relevant for any official build, is plugin support. An ARM host requires either ARM plugins or a way to load Intel ones. The former can be provided with an ARM build of the Vamp Plugin Pack. Alternatively or additionally, SV could gain a way to load both plugin architectures with an extra external helper build - it already does this on Windows where both 32-bit and 64-bit Intel plugins are supported by the 64-bit host. That would be closer to ideal, but it would take some actual programming.

There is a symmetry there - one of the things that makes the build fiddly is the use of generated Cap'n Proto schema code to communicate between SV and the external plugin helper process, and one reason for the existence of the external helper process is to support multiple plugin architectures, as it does on Windows. So in a way it seems a pity to suffer the pain (the tricky parts of the build) without reaping the reward (architecture-independent plugin support).

My provisional idea therefore has been to do this "properly" - with multiple architecture support for plugins - but as that will take a week or two, the timing depends very much on other work. In my mental timeline that means some time in June, I think.

**Comment by cannam** [comment]
A little later than planned, but we now have an arm64/x86_64 universal binary that is capable of loading and using Vamp plugins of both architectures (on arm64 of course). You can try it with the v4.4-pre2 test build available for download currently from https://sonicvisualiser.org/pre/ (a temporary location - I am about to revisit the question of which files get hosted where, as the SoundSoftware code site is still having cert issues and Bintray has ceased operating).

Please give this a try, and add any comments specifically about architecture compatibility and plugin loading here. (If you find other problems with this pre-release, please open another issue or drop me a line by email.)

**Comment by yairchu** [comment]
The build now works for me!

These were my local steps:

```zsh
brew install qt5 smlnj meson ninja
PATH=$PATH:/usr/local/smlnj/bin ./repoint install
PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig" meson build
ninja -C build
```

**Comment by cannam** [comment]
4.4 is a universal binary now; closing. Updated Vamp Plugin Pack is still pending but that's a separate project...
