### ISSUE TITLE
Delete Shortcut does not work on Mac

### ISSUE THREAD

**Issue by SamuelMiller** [sonic-visualiser/sonic-visualiser#30]
In Catalina Mac OS, SV 4.3, hitting the delete key does not delete any selected time instances. In order to delete them, I have to use the top menu (Edit > Delete Selected Instances).

**Comment by cannam** [comment]
Just tried this and it does work for me.

I imagine the confusion arises because the key shortcut is actually Delete, not Backspace - and Macs don't have a Delete key so you have to use Fn+Backspace.

Most of SV's shortcuts were devised on an external PC keyboard with numpad, hence some curios like the use of the numpad Enter key as the original shortcut for inserting a time instant. (We later added ";" as an alternative but numpad-Enter does still work too.)

**Comment by SamuelMiller** [comment]
Reading up on it. Even though the key on the Macbook says "Delete" it acts more like a backward key. Fn+Delete does work. I didn't know that the "forward-delete" symbol listed in the Edit menu meant fn+delete. Thanks for letting me know.
