### ISSUE TITLE
allow disabling waveform interpolation

### ISSUE THREAD

**Issue by mi-art** [sonic-visualiser/sonic-visualiser#34]
Hi there,

I would like to be able to disable waveform interpolation, because when analysing audio files, it hides the real start of the playback.

With a linear scale, I can at least zoom a lot and see that samples are actually at 0:

![image](https://user-images.githubusercontent.com/38841779/140540188-9efce9d2-11df-40bf-8d44-41398d18d1b5.png)

However, with the dB scale, which would be extremely useful to know when the file stopped being pure zeros, the interpolation makes it impossible to see where it actually started:

![image](https://user-images.githubusercontent.com/38841779/140541169-79203ac4-be09-48d4-bd31-f79f7f52ea15.png)

Cheers,

Arthur

**Comment by lopho** [comment]
Interested as well, as I'm currently developing bandlimiting methods for synthesis, and comparison between a raw saw and a bandlimited saw is hard, when the raw saw is being interpolated like this.

View in Audacity:
![audacity_raw_saw](https://user-images.githubusercontent.com/1366969/145676979-55302330-360b-420d-baa6-a0b3732aa75c.png)
View in Sonic Vis:
![sonic_raw](https://user-images.githubusercontent.com/1366969/145676992-4ae721ce-4692-4029-914c-aa04ad4b25df.png)

**Comment by cannam** [comment]
Very good points both - I will look at this when I next get a slice of time for updates to SV. Sorry to take a while to reply about this; will be soon I hope.

**Comment by cannam** [comment]
I've committed a change that does this - so it will be in 4.4.1, or whatever the next release is, one way or another.

I haven't yet made a decision on what to do instead of interpolating the curve. At the moment it just displays the same little squares for the actual sample positions, omitting the curve behind them so they are standing totally in isolation. We could have stems like in Audacity (which I like well enough), or something else, or perhaps it's even ok with just the points - any thoughts?

![Screenshot from 2022-03-03 11-29-58](https://user-images.githubusercontent.com/104933/156556256-68149cfb-8092-482b-ad31-94b9b246b128.png)

**Comment by mi-art** [comment]
I think the stems might not help when visualising several signals on the same pane because they'd hide the signal behind.

![image](https://user-images.githubusercontent.com/38841779/156574947-ce07c14f-6337-4661-a312-5a4e4381e03d.png)

**Comment by lopho** [comment]
Nice, thanks!

As it depends on the kind of view I try to setup (vertical, stacked, etc.), making the display type optional (stem, linear e.g. line connected, or only dots) would be nice.

**Comment by cannam** [comment]
I took the view that a simple toggle was probably preferable to a more complex control, and have released v4.5 with that in place.
