### ISSUE TITLE
undefined symbol: __ext_finite

### ISSUE THREAD

**Issue by opyate** [sonic-visualiser/sonic-visualiser#67]
Hello, 

I downloaded the app from the Github releases page, and installed it like this:

```
sudo dpkg -i ~/Downloads/sonic-visualiser_4.5.1_amd64.deb
```

I see this when I start sonic visualiser:

![image](https://user-images.githubusercontent.com/96808/211852026-210f514d-2ca7-4890-917a-fa463bc7b368.png)

At first, I tried to reinstall the libs in the error message, to no avail:

```
sudo apt --only-upgrade install autotalent csladspa
```

I'm using https://github.com/nektos/act to build it straight from your Github workflow, so I can get a repeatable build, and play around with the Makefile (it might need an extra linking step since [this change in glibc](https://sourceware.org/pipermail/libc-alpha/2020-May/113773.html), so I want to test that).

Here are my steps so far:

```
git clone https://github.com/sonic-visualiser/sonic-visualiser
cd sonic-visualiser
git checkout sv_v4.5.1
# --reuse keeps the Github Action container around
act --reuse  -W .github/workflows/linux.yml
cd $(mktemp -d)
# copy the build directory to a temp location
docker cp <container_id>:/home/opyate/Documents/sonic-visualiser/build/ .
./build/sonic-visualiser                                                                                                                                                                             
```

That last command has an error:

```
./build/sonic-visualiser: symbol lookup error: ./build/sonic-visualiser: undefined symbol: _ZNK10RubberBand19RubberBandStretcher16getEngineVersionEv
```

Perhaps I'm missing a step which isn't defined in the Github Workflows, i.e. how do you package the final binary that you put on your releases page?

**Comment by cannam** [comment]
You appear to have two separate problems here

1. Some LADSPA plugins on your system have undefined symbols and cannot be loaded, or are completely empty - hence the dialog. This doesn't appear to have anything to do with Sonic Visualiser itself, unless the dialog is actually wrong. I don't think I know enough to comment meaningfully about any specific plugin builds. The error should not actually prevent SV from working or from loading any other plugins - it should be no more than annoying.
2. The SV build you made from the Github CI action doesn't run on another system.

The reason for problem 2 is that the Github CI script builds and installs a newer version of the Rubber Band library than was available in its base distro, but the library that it builds is a dynamic library, so it would need to be also installed on any other system you wanted to run the compiled SV binary on.

Your options would be: install a newer Rubber Band library on the target system as well; or modify the build script to only make a static library for Rubber Band so that it is statically linked in the resulting SV binary. To do the latter, add `-Ddefault_library=static` to the `meson build` invocation at line 45 of linux.yml.

The official package binaries are built using Docker scripts in `deploy/linux` - see for example `deploy/linux/docker/Dockerfile_deb.in` which is configured and invoked from the script `deploy/linux/deploy-deb.sh`. In this script the same Rubber Band library version is installed, but this time with `-Ddefault_library=static`. It would not be unreasonable to modify the Github CI script to do the same thing generally, I guess.

**Comment by opyate** [comment]
> The error should not actually prevent SV from working or from loading any other plugins - it should be no more than annoying.

You're right - sonic visualiser actually does what I need it to do at the moment, so I'll put a pin in this.
If I need LADSPA, I'll just build it from source.

Thanks for the app! :+1:
