### ISSUE TITLE
Glitch in spectrogram's -inf color threshold

### ISSUE THREAD

**Issue by danadam** [sonic-visualiser/sonic-visualiser#92]
version: 4.5.2

Color threshold takes values from -81 to -1 and -81 means -inf. When a new spectrogram is added, its color threshold is set to -inf and, AFAICT, at that moment it actually translates to about -150 dBFS. When you change the threshold to not -inf, so for example -80 and then back to -inf, then now it translates to about -200 dBFS.

To demonstrate, I attached a 32-bit [x.wav.zip](https://github.com/user-attachments/files/15519953/x.wav.zip) file, which contains 4 tones with increasing amplitudes:

* 4 kHz, from -50 to 0 dBFS
* 8 kHz, from -100 to -50 dBFS
* 12 kHz, from -150 to -100 dBFS
* 16 kHz, from -200 to -150 dBFS

Add two panes with Spectrogram, notice that in both panes nothing is visible below -150 dBFS:
![01 new panes](https://github.com/sonic-visualiser/sonic-visualiser/assets/170743/279aa981-b296-432e-bb6c-ba5d4ee6ff3c)

Double click on Color threshold setting of the top pane to edit the threshold:
![02 threshold](https://github.com/sonic-visualiser/sonic-visualiser/assets/170743/65b76dfe-9669-431b-ad8b-8833066cccde)

Enter `-80`, notice that in the top pane nothing is visible below -80 dBFS:
![03 threshold 80](https://github.com/sonic-visualiser/sonic-visualiser/assets/170743/09664845-55d3-4ccf-a895-970d6ac6d2d2)

Edit the threshold again and set it back to `-81`, notice that in the top pane the signal is now visible down to about -200 dBFS:
![04 threshold inf](https://github.com/sonic-visualiser/sonic-visualiser/assets/170743/9c498d77-1560-479a-820a-f384039de2f1)

**Comment by cannam** [comment]
Can confirm (and thank you for the excellent test data)

**Comment by cannam** [comment]
This was a problem left over from an incomplete fix to the former "idiosyncratic" use of 10log10 (instead of the expected 20log10) for dB values a few years ago.

The default threshold was set in the `SpectrogramLayer` constructor to 1.0e-8, or -160dB. But the bottom end of the range in the dial control remained -80, or -81 given the (intentional) hack to make the bottom value equivalent to -Inf. Thus the default value was not actually selectable using the control - the best you could get was either -80 or -Inf.

The fix is to adjust the range in the control so that it is now -161 to -1 with -161 being -Inf and the others being dB values, with -160 equal to the default (which is unchanged in absolute value).

This is still a rubbish way to set the value in UI terms, especially for -Inf, but it should fix the mathematical problem.
