### ISSUE TITLE
are there any plans for a .clap plugin release?

### ISSUE THREAD

**Issue by RustoMCSpit** [sonic-visualiser/sonic-visualiser#93]

**Comment by RustoMCSpit** [comment]
sorry im getting my head around all of this right now. to my understanding this is a plugin host and it accepts its own custom-ly developed "vamp" format (rather than any mainstream format such as lv2, clap, vst3).

what i am asking for here is that can sonic visualiser itself be made into a clap plugin so i can run it inside a daw (alongside its plugins running inside of it). to my understanding this is an open source equilavent of transcribe! and tony is an open source equilavent to melodyne / neuralnote (except neuralnote is polyphonic but it's also foss https://github.com/DamRsn/NeuralNote ). please inform me of any of my understanding is off!

**Comment by RustoMCSpit** [comment]
.clap is open source by the way https://github.com/free-audio/clap

**Comment by cannam** [comment]
Thanks for elaborating! Your reply came up just as I was trying to figure out what you were asking for.

Sonic Visualiser is a host application, that can load audio analysis plugins (Vamp, fundamentally different from an effects plugin format) and can also load and apply effects plugins (but only in the antique LADSPA format).

It would be reasonable to add CLAP host support to SV so that it could also load CLAP effects plugins. To my mind, in terms of priority, that would probably be some way behind VST3 and perhaps LV2, neither of which has ever quite reached the top of the to-do list, but it's certainly not a bad idea.

Adapting SV itself into a real-time effect plugin format doesn't seem enormously useful to me because its visualisations and analyses are largely non-real-time, so it would have to tediously buffer up all of its input and then analyse it offline, or else just load audio directly from disc bypassing the DAW entirely. Of course some analysis-type plugins do this anyway, it's just a bit limited.

Adapting SV into a random-access plugin format (e.g. ARA, as developed for use with Melodyne) makes more sense to me, and in fact I've recently been working at QM on a project somewhat related to that, although it doesn't have any visible output yet.

(I'm not sure whether CLAP has any random-access capabilities like ARA, so I don't know which of the above it resembles. Practically speaking the level of support for ARA varies enormously between hosts as well, even among those that nominally support it at all)

A big sticking point is support; maintaining plugins that work across the caprices of various hosts as well as supporting the standalone app looks like a significant extra burden.

And just for background, I wouldn't actually describe SV as an equivalent of Transcribe, or anything in particular actually - it's not ideal for transcription, though that's one of the things it can be used for. It's really a general toolbox for close study of music audio. Similarly Tony is not much like either Melodyne or NeuralNote because it's not intended at all for studio or compositional use, only for precise annotation. The output of a successful use of Tony is more likely to be a .csv file than music!

Both SV and Tony are quite "researchy" tools. They do have wider uses, but apps directly designed for those uses (e.g. Transcribe, Capo, Melodyne etc) will often do a better job at them.

**Comment by RustoMCSpit** [comment]
> It would be reasonable to add CLAP host support to SV so that it could also load CLAP effects plugins. To my mind, in terms of priority, that would probably be some way behind VST3 and perhaps LV2, neither of which has ever quite reached the top of the to-do list, but it's certainly not a bad idea.

i disagree. VST is not FOSS while CLAP is, you can PR code to CLAP which is also written in C++ (but predominantly C). CLAP is rapidly growing and linux support is great https://github.com/RustoMCSpit/awesome-linux-clap-list

**Comment by RustoMCSpit** [comment]
> Adapting SV itself into a real-time effect plugin format doesn't seem enormously useful to me because its visualisations and analyses are largely non-real-time, so it would have to tediously buffer up all of its input and then analyse it offline, or else just load audio directly from disc bypassing the DAW entirely. Of course some analysis-type plugins do this anyway, it's just a bit limited.

i see... i mean the codebase could be refactored but that would be a large effort. i still see a use in having it in a daw as a plugin but thats more just a convenience in that it can interact with a daw more easily

**Comment by RustoMCSpit** [comment]
> Adapting SV into a random-access plugin format (e.g. ARA, as developed for use with Melodyne) makes more sense to me, and in fact I've recently been working at QM on a project somewhat related to that, although it doesn't have any visible output yet.

QM? also is this project FOSS

**Comment by RustoMCSpit** [comment]
> And just for background, I wouldn't actually describe SV as an equivalent of Transcribe, or anything in particular actually - it's not ideal for transcription, though that's one of the things it can be used for. It's really a general toolbox for close study of music audio. Similarly Tony is not much like either Melodyne or NeuralNote because it's not intended at all for studio or compositional use, only for precise annotation. The output of a successful use of Tony is more likely to be a .csv file than music!

well surely some of the features are desirable, such as letting Tony be able to pitch shift audio like Melodyne can? are you just tryign to keep the scope small? granted something as large as https://hitnmix.com/ ripx is obviously feature creep but are you against taking inspiration from some of both of their features as your interface and general premise seems very akin, even somewhat like what izotope does or https://products.zplane.de/products/decoda/

**Comment by RustoMCSpit** [comment]
i mean, real-time applications of certain things is definitely possible https://github.com/chipnertkj/chipbox/issues/10

**Comment by cannam** [comment]
> i disagree. VST is not FOSS while CLAP is

VST3 is GPLv3, has Linux support, and I assume is still used by quite a lot more plugins than CLAP. Not that I have any great love for it, just from a pragmatic perspective.

> well surely some of the features are desirable, such as letting Tony be able to pitch shift audio like Melodyne can? are you just tryign to keep the scope small?

Not just small but specific - Tony is designed for a single use-case, precise human-reviewed annotation of singing pitch. Anything that makes it worse for that purpose is something that should be in a different application.

The world of audio software is vast and our resources are tiny. I've worked on Free Software projects before whose scope blew up to such an extent as to make them almost impossible to implement, test, and maintain. It's no bad thing to occupy a niche!

**Comment by RustoMCSpit** [comment]
> VST3 is GPLv3, has Linux support, and I assume is still used by quite a lot more plugins than CLAP. Not that I have any great love for it, just from a pragmatic perspective.

i never knew it was dual licensed!!

> Not just small but specific - Tony is designed for a single use-case, precise human-reviewed annotation of singing pitch. Anything that makes it worse for that purpose is something that should be in a different application.

i see, and it's solely monophonic and will never try be polyphonic? again neuralnote uses foss means to calculate polyphonic audio and display them via midi
